
                 INSERT INTO ABSTRUC_DATA VALUES('12e8',
                                                 1.90,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('15c8',
                                                 2.50,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a0q',
                                                 2.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a14',
                                                 2.50,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a2y',
                                                 1.50,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a3l',
                                                 1.95,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a3r',
                                                 2.10,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a4j',
                                                 2.10,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a4k',
                                                 2.40,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a5f',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a6t',
                                                 2.70,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a6u',
                                                 2.10,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a6v',
                                                 1.80,
                                                 0.30,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a6w',
                                                 2.00,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a7n',
                                                 2.01,
                                                 0.15,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a7o',
                                                 2.00,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a7p',
                                                 2.01,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a7q',
                                                 2.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1a7r',
                                                 2.01,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1acy',
                                                 3.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ad0',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ad9',
                                                 2.80,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1adq',
                                                 3.15,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ae6',
                                                 3.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1afv',
                                                 3.70,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ahw',
                                                 3.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ai1',
                                                 2.80,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1aif',
                                                 2.90,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1aj7',
                                                 2.10,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ap2',
                                                 2.36,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1aqk',
                                                 1.84,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ar1',
                                                 2.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1axs',
                                                 2.60,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1axt',
                                                 2.15,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ay1',
                                                 2.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1b2w',
                                                 2.90,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1b4j',
                                                 2.90,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1baf',
                                                 2.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bbd',
                                                 2.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bbj',
                                                 3.10,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bey',
                                                 3.25,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bfo',
                                                 2.60,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bfv',
                                                 2.10,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bgx',
                                                 2.30,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bj1',
                                                 2.40,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bln',
                                                 2.80,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bm3',
                                                 2.00,
                                                 0.15,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bog',
                                                 2.60,
                                                 0.31,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bql',
                                                 2.60,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bvk',
                                                 2.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bvl',
                                                 2.87,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1bz7',
                                                 2.50,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1c08',
                                                 2.30,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1c12',
                                                 2.60,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1c1e',
                                                 1.90,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1c5b',
                                                 2.10,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1c5c',
                                                 1.61,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1c5d',
                                                 2.40,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1c9r',
                                                 3.50,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cbv',
                                                 2.66,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ce1',
                                                 1.90,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cf8',
                                                 2.70,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cfn',
                                                 2.65,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cfq',
                                                 2.80,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cfs',
                                                 2.75,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cft',
                                                 2.80,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cfv',
                                                 2.10,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cgs',
                                                 2.60,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cic',
                                                 2.50,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ck0',
                                                 2.50,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cl7',
                                                 3.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1clo',
                                                 2.10,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cly',
                                                 2.50,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1clz',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cr9',
                                                 2.00,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ct8',
                                                 2.20,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cu4',
                                                 2.90,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1cz8',
                                                 2.40,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1d5b',
                                                 2.80,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1d5i',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1d6v',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dba',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dbb',
                                                 2.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dbj',
                                                 2.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dbk',
                                                 3.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dbm',
                                                 2.70,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dee',
                                                 2.70,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dfb',
                                                 2.70,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dl7',
                                                 2.35,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dlf',
                                                 1.45,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dn0',
                                                 2.28,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dqd',
                                                 2.10,
                                                 0.32,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dqj',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dql',
                                                 2.60,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dqm',
                                                 2.10,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dqq',
                                                 1.80,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dsf',
                                                 2.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dvf',
                                                 1.90,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1dvf',
                                                 1.90,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1e4w',
                                                 1.95,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1e4x',
                                                 1.90,
                                                 0.31,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1e6j',
                                                 3.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1e6o',
                                                 1.80,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1eap',
                                                 2.40,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ehl',
                                                 2.40,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ejo',
                                                 2.30,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1emt',
                                                 2.25,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1eo8',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1etz',
                                                 2.60,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ezv',
                                                 2.30,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1f11',
                                                 3.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1f3d',
                                                 1.87,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1f4w',
                                                 2.30,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1f4x',
                                                 2.30,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1f4y',
                                                 2.80,
                                                 0.35,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1f58',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1f8t',
                                                 2.20,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1f90',
                                                 2.60,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fai',
                                                 2.70,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fbi',
                                                 3.00,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fdl',
                                                 2.50,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fe8',
                                                 2.03,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fgn',
                                                 2.50,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fgv',
                                                 1.90,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fh5',
                                                 2.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fig',
                                                 3.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fj1',
                                                 2.68,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fl3',
                                                 2.45,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1flr',
                                                 1.85,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fn4',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fns',
                                                 2.00,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1for',
                                                 2.75,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fpt',
                                                 3.00,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1frg',
                                                 2.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fsk',
                                                 2.90,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fvc',
                                                 2.20,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fvd',
                                                 2.50,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1fve',
                                                 2.70,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1g9m',
                                                 2.20,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1g9n',
                                                 2.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1gaf',
                                                 1.95,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1gc1',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ggb',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ggc',
                                                 2.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ggi',
                                                 2.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ghf',
                                                 2.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1gig',
                                                 2.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1gm3',
                                                 2.60,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1gpo',
                                                 1.95,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1h0d',
                                                 2.00,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1h3p',
                                                 2.60,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hh6',
                                                 2.60,
                                                 0.34,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hh9',
                                                 2.70,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hi6',
                                                 2.55,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hil',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1him',
                                                 2.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hin',
                                                 3.10,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hkl',
                                                 2.68,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hq4',
                                                 2.70,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hys',
                                                 3.00,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hyx',
                                                 1.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1hyy',
                                                 1.80,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1i3g',
                                                 2.44,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1i8i',
                                                 2.40,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1i8k',
                                                 1.80,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1i8m',
                                                 2.10,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1i9i',
                                                 2.72,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1i9j',
                                                 2.60,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1i9r',
                                                 3.10,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1iai',
                                                 2.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1iai',
                                                 2.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ibg',
                                                 2.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ic4',
                                                 2.50,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ic5',
                                                 2.30,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ic7',
                                                 2.10,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ifh',
                                                 2.80,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1igc',
                                                 2.60,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1igf',
                                                 2.80,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1igi',
                                                 2.70,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1igj',
                                                 2.50,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1igm',
                                                 2.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ikf',
                                                 2.50,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1il1',
                                                 2.20,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ind',
                                                 2.20,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ine',
                                                 2.80,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1iqd',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1iqw',
                                                 2.50,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1it9',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1j05',
                                                 1.50,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1j1o',
                                                 1.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1j1p',
                                                 1.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1j1x',
                                                 1.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1j5o',
                                                 3.50,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jel',
                                                 2.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jfq',
                                                 1.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jgl',
                                                 2.15,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jhk',
                                                 2.51,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jhl',
                                                 2.40,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jn6',
                                                 2.70,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jnh',
                                                 2.85,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jnl',
                                                 3.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jnn',
                                                 3.20,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jps',
                                                 1.85,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jpt',
                                                 1.85,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1jrh',
                                                 2.80,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1k4c',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1k4d',
                                                 2.30,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1k6q',
                                                 2.40,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1kb5',
                                                 2.50,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1kcv',
                                                 1.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1keg',
                                                 2.40,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1kel',
                                                 1.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1kem',
                                                 2.20,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ken',
                                                 3.50,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1kfa',
                                                 2.80,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1kip',
                                                 2.10,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1kiq',
                                                 1.85,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1kir',
                                                 2.00,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1kno',
                                                 3.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ktr',
                                                 2.70,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1l7i',
                                                 1.80,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1l7t',
                                                 2.10,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1lk3',
                                                 1.91,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1lo0',
                                                 2.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1lo2',
                                                 2.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1lo3',
                                                 2.30,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1lo4',
                                                 2.40,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1m71',
                                                 2.80,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1m7d',
                                                 2.30,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1m7i',
                                                 2.50,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mam',
                                                 2.45,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mcp',
                                                 2.70,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mf2',
                                                 2.60,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mfa',
                                                 1.70,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mfb',
                                                 2.10,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mfc',
                                                 2.10,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mfd',
                                                 2.10,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mfe',
                                                 2.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mh5',
                                                 2.10,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mhh',
                                                 2.10,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mhp',
                                                 2.80,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mim',
                                                 2.60,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mj8',
                                                 1.75,
                                                 0.15,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mjj',
                                                 2.10,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mju',
                                                 1.22,
                                                 0.12,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mlb',
                                                 2.10,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mlc',
                                                 2.50,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mnu',
                                                 2.50,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mpa',
                                                 2.60,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mqk',
                                                 1.28,
                                                 0.14,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mrc',
                                                 2.40,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mrd',
                                                 2.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mre',
                                                 2.30,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mrf',
                                                 2.40,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1mvu',
                                                 1.78,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1n4x',
                                                 1.70,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1n5y',
                                                 3.10,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1n64',
                                                 2.34,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1n6q',
                                                 3.00,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1n8z',
                                                 2.52,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nbv',
                                                 2.00,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nc2',
                                                 2.10,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nc4',
                                                 2.25,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nca',
                                                 2.50,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ncb',
                                                 2.50,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ncc',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ncd',
                                                 2.90,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ncw',
                                                 1.30,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nd0',
                                                 2.45,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ndg',
                                                 1.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ndm',
                                                 2.10,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nfd',
                                                 2.80,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ngp',
                                                 2.40,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ngq',
                                                 2.40,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ngw',
                                                 2.60,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ngx',
                                                 1.80,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ngy',
                                                 2.20,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ngz',
                                                 1.60,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nld',
                                                 2.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nma',
                                                 3.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nmb',
                                                 2.20,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1nsn',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1oak',
                                                 2.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1oaq',
                                                 1.50,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1oar',
                                                 2.22,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1oau',
                                                 1.80,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1oax',
                                                 2.66,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1oay',
                                                 2.66,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1oaz',
                                                 2.77,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ob1',
                                                 2.90,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ocw',
                                                 2.01,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1om3',
                                                 2.20,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1op3',
                                                 1.75,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1op5',
                                                 3.00,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1opg',
                                                 2.00,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1orq',
                                                 3.20,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ors',
                                                 1.90,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1osp',
                                                 1.95,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ots',
                                                 2.51,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ott',
                                                 3.00,
                                                 0.30,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1otu',
                                                 3.30,
                                                 0.29,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1p4b',
                                                 2.35,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1p4i',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1p7k',
                                                 1.75,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1pg7',
                                                 2.50,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1plg',
                                                 2.80,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1psk',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1pz5',
                                                 1.80,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q0x',
                                                 1.60,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q0y',
                                                 2.00,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q1j',
                                                 2.50,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q72',
                                                 1.70,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q9k',
                                                 1.96,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q9l',
                                                 2.28,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q9o',
                                                 1.79,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q9q',
                                                 1.49,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q9r',
                                                 1.45,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q9t',
                                                 1.74,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q9v',
                                                 1.73,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1q9w',
                                                 1.75,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qbl',
                                                 2.26,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qbm',
                                                 2.37,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qfu',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qfw',
                                                 3.50,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qgc',
                                                 30.00,
                                                 0.00,
                                                 'High-resolution microscopy');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qkz',
                                                 1.95,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qle',
                                                 3.00,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qlr',
                                                 2.83,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qnz',
                                                 0.00,
                                                 0.00,
                                                 'NMR');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1qyg',
                                                 1.81,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1r0a',
                                                 2.80,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1r24',
                                                 3.10,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1r3i',
                                                 2.40,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1r3j',
                                                 1.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1r3k',
                                                 2.80,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1r3l',
                                                 2.41,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rfd',
                                                 2.09,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rhh',
                                                 1.90,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rih',
                                                 2.50,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1riu',
                                                 2.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1riv',
                                                 2.20,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rjl',
                                                 2.60,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rmf',
                                                 2.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ru9',
                                                 2.50,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rua',
                                                 1.75,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ruk',
                                                 1.40,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rul',
                                                 1.88,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rum',
                                                 1.48,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rup',
                                                 1.40,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ruq',
                                                 1.86,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rur',
                                                 1.50,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rvf',
                                                 4.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rz7',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rz8',
                                                 2.30,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rzf',
                                                 1.70,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rzg',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rzi',
                                                 2.90,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rzj',
                                                 2.20,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1rzk',
                                                 2.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1s3k',
                                                 1.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1s5h',
                                                 2.20,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1s5i',
                                                 2.70,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1s78',
                                                 3.25,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1sbs',
                                                 2.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1sm3',
                                                 1.95,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1sy6',
                                                 2.10,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1t03',
                                                 3.10,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1t04',
                                                 3.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1t3f',
                                                 2.00,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1t4k',
                                                 2.50,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1t66',
                                                 2.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1tet',
                                                 2.30,
                                                 0.15,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1tjg',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1tpx',
                                                 2.56,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1tqb',
                                                 2.55,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1tqc',
                                                 2.80,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1tzh',
                                                 2.60,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1tzi',
                                                 2.80,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8h',
                                                 2.10,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8i',
                                                 2.00,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8j',
                                                 2.24,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8k',
                                                 2.24,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8l',
                                                 2.60,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8m',
                                                 2.40,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8n',
                                                 2.56,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8o',
                                                 3.02,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8p',
                                                 3.23,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u8q',
                                                 2.24,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u91',
                                                 2.24,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u92',
                                                 2.24,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u93',
                                                 2.37,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u95',
                                                 2.24,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ua6',
                                                 1.90,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1uac',
                                                 1.70,
                                                 0.15,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ucb',
                                                 2.50,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1uj3',
                                                 2.10,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1uwe',
                                                 2.67,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1uwg',
                                                 2.79,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1uz6',
                                                 2.05,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1uz8',
                                                 1.80,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1v7m',
                                                 2.51,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1v7n',
                                                 3.30,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1vfa',
                                                 1.80,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1vfb',
                                                 1.80,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1vge',
                                                 2.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1w72',
                                                 2.15,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1wej',
                                                 1.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1xiw',
                                                 1.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yec',
                                                 1.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yed',
                                                 3.10,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yee',
                                                 2.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yef',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yeg',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yeh',
                                                 2.55,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yuh',
                                                 3.00,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('25c8',
                                                 2.00,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ap2',
                                                 2.40,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2bfv',
                                                 2.50,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2cgr',
                                                 2.20,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ck0',
                                                 2.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dbl',
                                                 2.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dlf',
                                                 1.55,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2f19',
                                                 2.80,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2f58',
                                                 2.80,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2f5a',
                                                 2.05,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2f5b',
                                                 2.00,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fb4',
                                                 1.90,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fbj',
                                                 1.95,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fgw',
                                                 3.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2gfb',
                                                 3.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2h1p',
                                                 2.40,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hmi',
                                                 2.80,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hrp',
                                                 2.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2iff',
                                                 2.65,
                                                 0.01,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ig2',
                                                 3.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2igf',
                                                 2.80,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2jel',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2mcp',
                                                 3.10,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2mpa',
                                                 2.60,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2osp',
                                                 2.68,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2pcp',
                                                 2.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2rcs',
                                                 2.10,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2vir',
                                                 3.25,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2vis',
                                                 3.25,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2vit',
                                                 3.25,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('32c2',
                                                 3.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('35c8',
                                                 2.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3ck0',
                                                 3.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3f58',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3fct',
                                                 2.40,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hfl',
                                                 2.65,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hfm',
                                                 3.00,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('43c9',
                                                 2.20,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('43ca',
                                                 2.30,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('4fab',
                                                 2.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('6fab',
                                                 1.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('7fab',
                                                 2.00,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('8fab',
                                                 1.80,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1seq',
                                                 1.78,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1t2q',
                                                 1.83,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1tzg',
                                                 2.20,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1uwx',
                                                 2.20,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1uyw',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1wt5',
                                                 2.10,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1xcq',
                                                 3.50,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1xct',
                                                 3.05,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1xf2',
                                                 2.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1xf3',
                                                 2.30,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1xf4',
                                                 2.50,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1xf5',
                                                 2.60,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1y0l',
                                                 2.50,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1y18',
                                                 2.80,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yjd',
                                                 2.70,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ymh',
                                                 2.60,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yqv',
                                                 1.70,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yy8',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yy9',
                                                 2.60,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yyl',
                                                 2.75,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1yym',
                                                 2.20,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1za3',
                                                 3.35,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2a1w',
                                                 2.70,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2bob',
                                                 2.76,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2boc',
                                                 3.01,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1u6a',
                                                 2.81,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ynk',
                                                 2.10,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ynl',
                                                 1.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1zls',
                                                 2.00,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1zlu',
                                                 2.75,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1zlv',
                                                 2.33,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1zlw',
                                                 2.85,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2brr',
                                                 1.95,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2adg',
                                                 2.50,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2adi',
                                                 2.80,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2adj',
                                                 2.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1xgy',
                                                 2.71,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ztx',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2aab',
                                                 2.50,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1wc7',
                                                 2.33,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1z3g',
                                                 3.30,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2adf',
                                                 1.90,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1ynt',
                                                 3.10,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2aep',
                                                 2.10,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2aeq',
                                                 3.00,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fec',
                                                 3.97,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fed',
                                                 3.32,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fee',
                                                 3.20,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2d03',
                                                 1.97,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2exw',
                                                 3.20,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2exy',
                                                 3.10,
                                                 0.33,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ez0',
                                                 3.54,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2c1o',
                                                 2.75,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2c1p',
                                                 2.00,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ajs',
                                                 1.70,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2aju',
                                                 1.50,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ajv',
                                                 1.50,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ajx',
                                                 1.85,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ajy',
                                                 2.10,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ajz',
                                                 2.30,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ak1',
                                                 1.85,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fd6',
                                                 1.90,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fjf',
                                                 2.65,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fjg',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fjh',
                                                 3.10,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1wcb',
                                                 2.50,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1zan',
                                                 1.70,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('1zea',
                                                 1.78,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2aj3',
                                                 2.03,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2atk',
                                                 2.50,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2b2x',
                                                 2.20,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2bmk',
                                                 2.30,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dd8',
                                                 2.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2g75',
                                                 2.28,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2gki',
                                                 2.88,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2agj',
                                                 2.60,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2arj',
                                                 2.88,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2gsi',
                                                 2.81,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2h2p',
                                                 3.10,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2h2s',
                                                 3.10,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2a6d',
                                                 2.90,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2b0s',
                                                 2.30,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2b1a',
                                                 2.35,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2b1h',
                                                 2.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2bdn',
                                                 2.53,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2cju',
                                                 2.50,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2cjv',
                                                 2.90,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ddq',
                                                 2.35,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqt',
                                                 1.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqu',
                                                 1.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2g5b',
                                                 2.30,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2h9g',
                                                 2.32,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dtg',
                                                 3.80,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2g60',
                                                 1.85,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2h8p',
                                                 2.25,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hfe',
                                                 2.25,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hg5',
                                                 2.75,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hlf',
                                                 3.30,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ht2',
                                                 3.32,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ht3',
                                                 3.30,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ht4',
                                                 3.20,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2htk',
                                                 3.41,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2htl',
                                                 3.40,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2cmr',
                                                 2.00,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fat',
                                                 1.77,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hfg',
                                                 2.61,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2i5y',
                                                 2.20,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2i60',
                                                 2.40,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ih1',
                                                 2.40,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ih3',
                                                 1.72,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2d7t',
                                                 1.70,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fr4',
                                                 1.95,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fx7',
                                                 1.76,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fx8',
                                                 2.20,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2fx9',
                                                 2.10,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hjf',
                                                 2.90,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2nyy',
                                                 2.61,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2nz9',
                                                 3.79,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqc',
                                                 1.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqd',
                                                 1.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqe',
                                                 1.90,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqf',
                                                 2.50,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqg',
                                                 2.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqh',
                                                 2.30,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqi',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dqj',
                                                 1.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dwd',
                                                 2.60,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dwe',
                                                 2.50,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2gcy',
                                                 2.50,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2gjz',
                                                 2.65,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2gk0',
                                                 2.45,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hvj',
                                                 2.75,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hvk',
                                                 1.90,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2j4w',
                                                 2.50,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2j5l',
                                                 2.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2nxy',
                                                 2.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2nxz',
                                                 2.04,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ny0',
                                                 2.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ny1',
                                                 1.99,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ny2',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ny3',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ny4',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ny5',
                                                 2.50,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ny6',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ny7',
                                                 2.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2dtm',
                                                 2.25,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2gsg',
                                                 2.10,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2itc',
                                                 3.20,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2itd',
                                                 2.70,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2j88',
                                                 2.60,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2nlj',
                                                 2.52,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ntf',
                                                 3.18,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2op4',
                                                 2.85,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2osl',
                                                 2.60,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2pw1',
                                                 2.60,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2pw2',
                                                 2.55,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2uud',
                                                 2.90,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2jix',
                                                 3.20,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2eh7',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2eh8',
                                                 2.60,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2eiz',
                                                 1.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2eks',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hkf',
                                                 2.01,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hkh',
                                                 2.10,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2hwz',
                                                 1.80,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2i9l',
                                                 3.10,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ipt',
                                                 2.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2ipu',
                                                 1.65,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2iq9',
                                                 2.30,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2iqa',
                                                 2.00,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2jb5',
                                                 2.80,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2nr6',
                                                 2.81,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2o5x',
                                                 2.05,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2o5y',
                                                 2.85,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2o5z',
                                                 2.40,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2or9',
                                                 2.70,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2orb',
                                                 2.20,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2oz4',
                                                 2.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2q76',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2qad',
                                                 3.30,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2qhr',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2qqk',
                                                 2.75,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2qql',
                                                 3.10,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2qqn',
                                                 2.20,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2qr0',
                                                 3.50,
                                                 0.29,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r0k',
                                                 3.51,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r0l',
                                                 2.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r0w',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r0z',
                                                 2.10,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r29',
                                                 3.00,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r56',
                                                 2.80,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r8s',
                                                 1.95,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r9h',
                                                 3.10,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2v17',
                                                 1.65,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2yss',
                                                 2.40,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2z4q',
                                                 2.30,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2z91',
                                                 2.60,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2z92',
                                                 2.30,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2z93',
                                                 2.40,
                                                 0.30,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2zch',
                                                 2.83,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2zck',
                                                 3.10,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2zcl',
                                                 3.25,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3b2u',
                                                 2.58,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3b2v',
                                                 3.30,
                                                 0.29,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bae',
                                                 1.59,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bkc',
                                                 1.90,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bkj',
                                                 1.59,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bkm',
                                                 1.60,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bky',
                                                 2.61,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bt2',
                                                 2.50,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3c08',
                                                 2.15,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3c09',
                                                 3.20,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3cfb',
                                                 1.60,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3cfc',
                                                 1.70,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3cfd',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3cfe',
                                                 2.99,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3cfj',
                                                 2.60,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3cfk',
                                                 2.60,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3cle',
                                                 2.50,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3clf',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2uyl',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2v7n',
                                                 1.92,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3d9a',
                                                 1.20,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3det',
                                                 2.80,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2v7h',
                                                 2.80,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bz4',
                                                 1.80,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3c2a',
                                                 2.10,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3c5s',
                                                 2.00,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3c6s',
                                                 1.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3cmo',
                                                 2.30,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3csy',
                                                 3.40,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3d0v',
                                                 2.05,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3d85',
                                                 1.90,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3dro',
                                                 3.90,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2vwe',
                                                 3.40,
                                                 0.29,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3b9k',
                                                 2.70,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bdy',
                                                 2.60,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3be1',
                                                 2.90,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bn9',
                                                 2.17,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bqu',
                                                 3.00,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bsz',
                                                 3.38,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3cxd',
                                                 2.80,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3dsf',
                                                 2.80,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3dvg',
                                                 2.60,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3dvn',
                                                 2.70,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bgf',
                                                 3.00,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3dur',
                                                 1.86,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3dus',
                                                 1.95,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3duu',
                                                 1.95,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3dv4',
                                                 1.95,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3dv6',
                                                 1.95,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eo0',
                                                 1.75,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eo1',
                                                 3.10,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r1w',
                                                 1.70,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r1x',
                                                 1.60,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r1y',
                                                 1.60,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r23',
                                                 1.65,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r2b',
                                                 1.60,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r2e',
                                                 2.40,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2r2h',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2zpk',
                                                 1.80,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3bpc',
                                                 1.85,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eot',
                                                 1.90,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eyf',
                                                 2.30,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eyo',
                                                 2.50,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eyq',
                                                 2.40,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2vxq',
                                                 1.90,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2vxs',
                                                 2.63,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2vxt',
                                                 1.49,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2vxu',
                                                 2.36,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2vxv',
                                                 1.49,
                                                 0.15,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2w60',
                                                 1.50,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2w65',
                                                 2.21,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2w9d',
                                                 1.57,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2w9e',
                                                 2.90,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2zkh',
                                                 2.04,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('2zuq',
                                                 3.30,
                                                 0.28,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3d69',
                                                 3.77,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3e8u',
                                                 2.10,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3ejy',
                                                 3.20,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3ejz',
                                                 2.90,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eo9',
                                                 1.80,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eoa',
                                                 2.80,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eob',
                                                 3.60,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eys',
                                                 1.95,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3eyu',
                                                 2.71,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3ffd',
                                                 2.00,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3fmg',
                                                 3.40,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3fn0',
                                                 1.80,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3fzu',
                                                 2.50,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3g6a',
                                                 2.10,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3g6d',
                                                 3.20,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3g6j',
                                                 3.10,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3gbm',
                                                 2.70,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3gbn',
                                                 2.20,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3ggw',
                                                 1.70,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3giz',
                                                 2.20,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3gje',
                                                 2.30,
                                                 0.23,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3gk8',
                                                 2.00,
                                                 0.27,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3grw',
                                                 2.10,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3h0t',
                                                 1.89,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3h42',
                                                 2.30,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hae',
                                                 2.90,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hb3',
                                                 2.25,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hns',
                                                 2.00,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hnt',
                                                 1.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hnv',
                                                 2.00,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3i2c',
                                                 2.80,
                                                 0.20,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3iy0',
                                                 12.50,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3iy3',
                                                 11.10,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3iy5',
                                                 18.00,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3iy6',
                                                 12.00,
                                                 0.00,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3g04',
                                                 2.55,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hc0',
                                                 1.90,
                                                 0.18,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hc3',
                                                 1.72,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hc4',
                                                 1.62,
                                                 0.16,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3gi8',
                                                 2.59,
                                                 0.26,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3gi9',
                                                 2.48,
                                                 0.25,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hi5',
                                                 2.50,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3hi6',
                                                 2.30,
                                                 0.17,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3i9g',
                                                 1.90,
                                                 0.19,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3ijh',
                                                 2.10,
                                                 0.21,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3ijs',
                                                 2.55,
                                                 0.22,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3ijy',
                                                 2.85,
                                                 0.24,
                                                 'crystal');
                
                 INSERT INTO ABSTRUC_DATA VALUES('3ikc',
                                                 2.60,
                                                 0.24,
                                                 'crystal');
                