>P1;ChainA
Sequence extracted from PDB file - By pdb2pir
DIELTQSPASLSVATGEKVTIRCMTSTDID
DDMNWYQQKPGEPPKFLISEGNTLRPGVPS
RFSSSGTGTDFVFTIENTLSEDVGDYYCLQ
SFNVPLTFGCGTKLEIk*
>P1;ChainB
Sequence extracted from PDB file - By pdb2pir
QVKLQQSGGGLVKPGASLKLSCVTSGFTFR
KFGMSWVRQTSDKCLEWVASISTGGYNTYY
SDNVKGRFTISRENAKNTLYLQMSSLKSED
TALYYCTRGYSSTSYAMDYWGQGTTVTVSg
iegr*
>P1;ChainC
Sequence extracted from PDB file - By pdb2pir
eekKGNYVVTDH*
